### ISSUE TITLE
This account is spam And thief !!!

### ISSUE THREAD

**Issue by OzzyOzmen** [nedenyap/nedenyap.github.io#1]
I reported this account because he just opened to send me a spam mesg . 
He also stealing someones repos to edit and show as himself project. He is thief. 
I believe that he doesnt deserve to be here

**Comment by nedenyap** [comment]
more than 7years i have this account LoL.get out here

**Comment by nedenyap** [comment]
When the sentence ends: Never. (Indefinite removal)

Reason for removal:You do not deserve to be a member of WM Tool with the Turkish and style you use. Your membership has been stopped.


DONT CURSE MAN!RUDE
![Opera Anlık Görüntü_2020-05-03_200426_wmaraci com](https://user-images.githubusercontent.com/9602844/80920570-6697b900-8d79-11ea-8c97-e75c1072d94f.png)

**Comment by OzzyOzmen** [comment]
it looks u r rubbish and waste man in the github platform because u just commented to my repos after clone and downloaded and i reported u on github and still u got big  brain issues.  Because u likes ur posts and comments and also always attack the posts owners after clone and download. U should shame on urself but i bet u will use translate to understand this msg thats way nothing will change about u. lol

And u know what u should learn english before try to piss anyone off.

**Comment by nedenyap** [comment]
lol i translate that picture cause everyone can understand.no lies.i guess i should think u dont have IQ to think of that sorry :)
i know english very well thx :*

report me pls like 1000times.lets see who i get ban ;)

i love how u cry xD

P:S : i didnt say i am owner i say u got banned webmaster sites.if u dont have IQ for reading i can write turkish xD

**Comment by OzzyOzmen** [comment]
still u can not write english lol. and stop acting like a child haha

anyway reported again.

**Comment by nedenyap** [comment]
:)) u so cool maan wow lol.just go play with sand :)

**Comment by nedenyap** [comment]
cut that weird beard and find a good lady.get a life xD.cy@
